[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin=lib/openzeppelin-contracts', '@openzeppelin-upgrades=lib/openzeppelin-contracts-upgradeable', '@fx-portal=lib/contracts', '@optimism=lib/optimism/packages/contracts', 'forge-std=lib/forge-std/src']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config